collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2123084
  brandStrength: 0.2921147
  lightness: 0.5645161
  brandColors:
    - '#20284B'
    - '#FBE044'
    - '#CEAD90'
    - '#80E166'
    - '#D71E27'
  rhythmicContrast: 0.3085475
typography_spectrum: 0.5844576
layout_spectrum: 0.7709637
name: My Travels
